//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tenda.EmpresaVenda.Domain.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://zeusqa.tenda.com/consultarnumerodepedido/service/process")]
        public string Tenda_EmpresaVenda_Domain_ConsultarNumeroPedidoZeus_ConsultarNumeroDePedido {
            get {
                return ((string)(this["Tenda_EmpresaVenda_Domain_ConsultarNumeroPedidoZeus_ConsultarNumeroDePedido"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://zeusqa.tenda.com/gerarrequisicaodecompra/service/process")]
        public string Tenda_EmpresaVenda_Domain_GerarRequisicaoDeCompraZeus_GerarRequisicaoCompra {
            get {
                return ((string)(this["Tenda_EmpresaVenda_Domain_GerarRequisicaoDeCompraZeus_GerarRequisicaoCompra"]));
            }
        }
    }
}
